name: Test Action

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run tests
        run: |
          echo "Running tests..."
          
      - name: Lint code with SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
